### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by nickveenhof**
Do not assume ID is called client id.

### CODE REVIEW

**Comment by pwolanin** [comment]
I think you are misinterpreting.  Maybe it's missing a possessive.

```
client's ID
```

**Comment by nickveenhof** [comment]
well, it's not necessarily a client id and in the beginning of the document we call it just the "id". We should be consistent and not suddenly introduce the word "client id".

**Comment by pwolanin** [comment]
Either way seems ok, but this is fine if you think it's going to reduce any
confusion.

On Mon, Feb 1, 2016 at 11:28 AM, Nick Veenhof notifications@github.com
wrote:

> well, it's not necessarily a client id and in the beginning of the
> document we call it just the "id". We should be consistent and not suddenly
> introduce the word "client id".
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/acquia/http-hmac-spec/pull/16#issuecomment-178056426.

## 

Peter M. Wolanin, Ph.D.      : Principal Cloud Security Engineer,  Acquia.
Inc.
peter.wolanin@acquia.com : 609-235-6869 (mobile) : 617-588-9863 (office)

**Comment by nickveenhof** [comment]
I made this PR because there was confusion (@ynx got confused) while writing a JS implementation. Merging it with your ok :) Thanks!

**Pull request merged**
